name: Lugx Gaming CI/CD Pipeline

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *' # Run tests hourly

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push game-service
      uses: docker/build-push-action@v4
      with:
        context: ./game-service
        file: ./game-service/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/lugx-game-service:latest

    - name: Build and push order-service
      uses: docker/build-push-action@v4
      with:
        context: ./order-service
        file: ./order-service/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/lugx-order-service:latest

    - name: Build and push lugx-analytics-service
      uses: docker/build-push-action@v4
      with:
        context: ./analytics-service
        file: ./analytics-service/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/lugx-analytics-service:latest

    - name: Build and push frontend-service
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/lugx-frontend-service:latest

  deploy-blue-green:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Configure Kubernetes context
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
        export KUBECONFIG=kubeconfig.yaml

    - name: Create namespaces if not exist
      run: |
        kubectl create namespace lugx-gaming-blue --dry-run=client -o yaml | kubectl apply -f -
        kubectl create namespace lugx-gaming-green --dry-run=client -o yaml | kubectl apply -f -

    - name: Deploy to Green environment
      run: |
        sed -i "s|image: lugx-game-service:latest|image: ${{ secrets.DOCKER_USERNAME }}/lugx-game-service:latest|g" kubernetes/game-service-deployment.yaml
        sed -i "s|image: lugx-order-service:latest|image: ${{ secrets.DOCKER_USERNAME }}/lugx-order-service:latest|g" kubernetes/order-service-deployment.yaml
        sed -i "s|image: lugx-analytics-service:latest|image: ${{ secrets.DOCKER_USERNAME }}/lugx-analytics-service:latest|g" kubernetes/analytics-service-deployment.yaml
        sed -i "s|image: lugx-frontend-service:latest|image: ${{ secrets.DOCKER_USERNAME }}/lugx-frontend-service:latest|g" kubernetes/frontend-deployment.yaml
        kubectl apply -f kubernetes/ -n lugx-gaming-green

    - name: Run integration tests
      run: |
        chmod +x ./tests/integration-test.sh
        ./tests/integration-test.sh

    - name: Switch traffic to Green
      run: |
        sed -i 's/lugx-gaming-blue/lugx-gaming-green/g' kubernetes/ingress.yaml
        kubectl apply -f kubernetes/ingress.yaml -n lugx-gaming

    - name: Clean up Blue environment
      run: |
        kubectl delete -f kubernetes/ -n lugx-gaming-blue || true

  periodic-tests:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run integration tests
      run: |
        chmod +x ./tests/integration-test.sh
        ./tests/integration-test.sh
