name: Lugx Gaming CI/CD Pipeline
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *'
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push game-service
      uses: docker/build-push-action@v4
      with:
        context: ./game-service
        file: ./game-service/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/lugx-game-service:blue
    - name: Build and push order-service
      uses: docker/build-push-action@v4
      with:
        context: ./order-service
        file: ./order-service/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/lugx-order-service:blue
    - name: Build and push lugx-analytics-service
      uses: docker/build-push-action@v4
      with:
        context: ./analytics-service
        file: ./analytics-service/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/lugx-analytics-service:blue
    - name: Build and push frontend-service
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/lugx-frontend-service:blue
  deploy-blue:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'
    - name: Configure Kubernetes context
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig.yaml
        export KUBECONFIG=kubeconfig.yaml
        kubectl config use-context minikube
    - name: Deploy to lugx-gaming with blue tag
      run: |
        sed -i "s|image: buddhinethmalshan/lugx-game-service:[^ ]*|image: ${{ secrets.DOCKER_USERNAME }}/lugx-game-service:blue|g" kubernetes/game-service-deployment.yaml
        sed -i "s|image: buddhinethmalshan/lugx-order-service:[^ ]*|image: ${{ secrets.DOCKER_USERNAME }}/lugx-order-service:blue|g" kubernetes/order-service-deployment.yaml
        sed -i "s|image: buddhinethmalshan/lugx-analytics-service:[^ ]*|image: ${{ secrets.DOCKER_USERNAME }}/lugx-analytics-service:blue|g" kubernetes/analytics-service-deployment.yaml
        sed -i "s|image: buddhinethmalshan/lugx-frontend-service:[^ ]*|image: ${{ secrets.DOCKER_USERNAME }}/lugx-frontend-service:blue|g" kubernetes/frontend-deployment.yaml
        kubectl apply -f kubernetes/ -n lugx-gaming --validate=false
    - name: Run integration tests
      run: |
        chmod +x ./tests/integration-test.sh
        ./tests/integration-test.sh
    - name: Rollback on test failure
      if: failure()
      run: |
        sed -i "s|image: buddhinethmalshan/lugx-game-service:[^ ]*|image: ${{ secrets.DOCKER_USERNAME }}/lugx-game-service:latest|g" kubernetes/game-service-deployment.yaml
        sed -i "s|image: buddhinethmalshan/lugx-order-service:[^ ]*|image: ${{ secrets.DOCKER_USERNAME }}/lugx-order-service:latest|g" kubernetes/order-service-deployment.yaml
        sed -i "s|image: buddhinethmalshan/lugx-analytics-service:[^ ]*|image: ${{ secrets.DOCKER_USERNAME }}/lugx-analytics-service:latest|g" kubernetes/analytics-service-deployment.yaml
        sed -i "s|image: buddhinethmalshan/lugx-frontend-service:[^ ]*|image: ${{ secrets.DOCKER_USERNAME }}/lugx-frontend-service:latest|g" kubernetes/frontend-deployment.yaml
        kubectl apply -f kubernetes/ -n lugx-gaming --validate=false
